name: Deploy k3s

on:
  workflow_run:
    workflows: ["Deploy Infrastructure"]
    types:
      - completed

jobs:
  deploy-k3s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy k3s master node
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.MASTER_IP }} "curl -sfL https://get.k3s.io | sh -"

      - name: Deploy k3s worker node 1
        run: |
          MASTER_IP=${{ env.MASTER_IP }}
          WORKER1_IP=${{ env.WORKER1_IP }}
          NODE_TOKEN=$(ssh -o StrictHostKeyChecking=no ubuntu@$MASTER_IP "sudo cat /var/lib/rancher/k3s/server/node-token")
          ssh -o StrictHostKeyChecking=no ubuntu@$WORKER1_IP "curl -sfL https://get.k3s.io | K3S_URL=https://$MASTER_IP:6443 K3S_TOKEN=$NODE_TOKEN sh -"

      - name: Deploy k3s worker node 2
        run: |
          MASTER_IP=${{ env.MASTER_IP }}
          WORKER2_IP=${{ env.WORKER2_IP }}
          NODE_TOKEN=$(ssh -o StrictHostKeyChecking=no ubuntu@$MASTER_IP "sudo cat /var/lib/rancher/k3s/server/node-token")
          ssh -o StrictHostKeyChecking=no ubuntu@$WORKER2_IP "curl -sfL https://get.k3s.io | K3S_URL=https://$MASTER_IP:6443 K3S_TOKEN=$NODE_TOKEN sh -"
